source 'https://rubygems.org'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'sqlite3'
# gem 'dm-mysql-adapter'
gem 'dm-rspec'
gem 'dm-noisy-failures'
gem 'pry'
gem 'pry-debugger'
gem 'factory_girl'

gem 'rspec'
